# Generated by Django 2.2.4 on 2021-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_delete_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
