# Generated by Django 2.2.4 on 2021-05-27 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_auto_20210526_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Birthday',
            field=models.DateField(default=datetime.date(2021, 5, 27)),
        ),
    ]
