# Generated by Django 2.2.4 on 2021-09-23 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_date',
            new_name='duedate',
        ),
    ]
