# Generated by Django 2.2.4 on 2021-05-28 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('coding_dojo_wall', '0002_auto_20210528_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='users',
        ),
        migrations.AddField(
            model_name='posts',
            name='owners',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ownerz', to='login.users'),
        ),
    ]
